= Frequently Asked Questions (FAQs)

These are some frequently asked questions and often encountered issues.

TIP: If you have a question regarding SSE-AT that is not answered here, please do not hesitate to ask it on the link:https://discord.gg/pqEHdWDf8z[Official Modding Forge Discord server].

== Do I have to edit any ini files?

Yes, make sure to set *[General]* > *sLanguage* in *Skyrim.ini* to your desired language (for eg. *GERMAN*).

Because voice files are not supported by SSE-AT, I also recommend switching to the English voice files in the same ini file. Just go to *[Archive]* and under *sResourceArchiveList2 replace Voices_xx0.bsa* with *Voices_en0.bsa*

== SSE-AT detected a mod file (or multiple) as _Translation Required_ although it contains no visible strings. What can I do to prevent it from detecting it again?

You can add it to the ignore list like this: Right click on the mod file(s) > *Add to Ignore List*. This prevents SSE-AT from including it at all.
The ignore list can be viewed via the "*Ignore List*" button right next to the filter button at the top.

== There are still untranslated strings in my game. I thought SSE-AT fixes this?

SSE-AT can only download translations that are available on Nexus Mods and automatically create translations for mods that are entirely covered by already installed translations (including vanilla strings).
Depending on your desired language, there are more or less available translations at Nexus Mods.

== I found untranslated strings from a mod that has a translation installed.

Please ensure that the original translation works and that it's a problem with SSE-AT before opening a Bug report or Issue.

== What languages are supported?

* Every language that is supported by the game is supported by SSE-AT. These languages are supported:
** Chinese
** French
** German
** Italian
** Japanese
** Polish
** Russian
** Spanish
* These languages are also supported by SSE-AT but not by the game. A database is not included for them.
** Korean
** Portuguese

== How do I update an installed translation after a mod update?

=== Translation has an update available online

If the translation was downloaded and has an update for the new mod version (check the version on its mod page), you can delete the old translation and download the updated translation. +
Follow these steps to update a translation:

. Delete the old translation from the SSE-AT database by making a right-click on it in the _Translations_ list and click on _Delete translation_.
. Select the original mod and its mod files.
. Make a right-click on one of them.
. Click on image:scan_online.svg[width=24px,height=24px] _Online scan..._ in the _Actions_ submenu.
. Wait for the online scan to complete. The mod files should now be blue (= _Translation available online_).
. Make sure that the mod and its files are still selected and make a right-click on one of them, again.
. Click on image:download_translations.svg[width=24px,height=24px] _Download available translations..._ in the _Actions_ submenu.
. Wait for the download list dialog to appear. Select the new translation version (if it is not pre-selected) and click on image:download_translations.svg[width=24px,height=24px] _Start downloads_.

=== Updating a translation yourself

If the translation was created by you or there is no update available, yet, you can update the translation yourself by following the steps xref:editor.adoc#_update_a_translation_after_a_mod_update[here].
