= Glossary for frequently used terms

== String

A _string_ is just a *piece of text* that appears *in-game*, such as a button label, item name or a dialogue line. You can think of a string as *a single "text block" that needs to be converted into another language*.

== Mod file

A _mod file_ is a file in a mod that may require a translation. This currently includes *traditional plugins* (.esp, .esm, .esl) and *interface translation files* (interface/*.txt) also known as _MCM translation files_.

== Output Mod

This is the mod generated by SSE-AT that includes *all translations that are installed and required for your mod list*. It is *installed at the bottom of your mod list*, together with Dynamic String Distributor.

== Dynamic String Distributor (or DSD in short)

This is an SKSE plugin that is able to *inject strings* into the game *without affecting the original plugins*. This means that an *outdated translation cannot "downgrade" the original plugin* that is installed in your mod list.
